//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funda_Trabajo_Parcial
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public int idProveedor { get; set; }
        public string nombre { get; set; }
        public string producto { get; set; }
        public double costo { get; set; }
        public string plan_de_pago { get; set; }
        public int id_EmpresaProveedor { get; set; }
    
        public virtual empresa empresa { get; set; }
    }
}
