//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funda_Trabajo_Parcial
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyecto
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public decimal costo { get; set; }
        public long idCliente { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
